### PR TITLE
Bugfixes

### LINKED ISSUE #18: Outdated app behaves unexpectedly
**Describe the bug**
Outdated versions of Skynet that are not supported by the server anymore behave unexpectedly.

**To Reproduce**
1. Take an outdated version of Skynet that is not supported by the server anymore
2. Delete all data to start with the `LoginActivity`
3. Create a new account
4. You are prompted that you have to update and confirm
5. Skynet shows "Creating account..."
6. You go to recent applications and go back to Skynet
7. The message "Creating account..." disappeared and we are back in the `CreateAccountActivity`

**Expected behavior**
In this case the application should close after confirming that the version is outdated.
If there is a session save on the device, the application should not close because users might want to read their messages but might not be able to update immediately because of a metered network.

**Screenshots**
Screenshot_1586208854

**Smartphone:**
 - Device: AOSP on IA Emulator (AVD)
 - OS: Android 9

### LINKED ISSUE #20: Missing public keys are not generated
**To Reproduce**
1. Create an account and login
2. Disconnect before `P18PublicKeys` has been delivered
3. Restart and reconnect
4. The client does not generate a new keypair

**Expected behavior**
The client has to create a new keypair even if a `P17PrivateKeys` exists in the loopback channel. A new keypair only becomes active once the server receives a `P18PublicKeys` which is referencing a `P17PrivateKeys`. Clients can create new keypairs at any time if dependencies are implemented correctly.

### LINKED ISSUE #26: Message formatting
There are few things related to message formatting that should be improved:
1. Large size emojis
_Special rendering for messages that only consist of emojis._
2. Message trimming
_Cut off white space chars at both ends of a message and find a reasonable line limit to prevent people from writing messages that take too long to scroll._
3. Markdown support
_Bold, italics and monospace. Other features will be added later._
4. Link detection
_The client should detect URLs in messages and display clickable links. For developers it would be very nice if messages like ASP.NET or Rocket.Chat would not be detected as links because they don't have a URI scheme and are written in uppercase._
5. Optimized rendering for multi line messages
_Long message have too much padding on the right side which wastes a lot of space on mobile devices._

### LINKED ISSUE #30: Inform the user about corrupted messages
Skynet uses `HMAC-SHA-256` to validate the integrity of an encrypted channel message. Therefore, the server has no possibility to detect and reject corrupted messages.

Messages with `MessageFlags.Loopback` are only accessible for the owning account. Corrupted messages can only be result of programming mistakes. The user should be able to report such an issue but there is not much explanation necessary.

Messages without `MessageFlags.Loopback` that were sent by other accounts can be corrupted because the other party used a modified client. For `P20ChatMessage` and `P21MessageOverride` a special rendering has to be implemented. In my opinion it is not necessary to inform the user if a valid message has a corrupted edit and another valid edit.

Once we implement groups, I will open a new issue because a corrupted `P1DGroupChannelKeyNotify` can have fatal consequences. Profile data channels will come with similar problems for many other packets.

### LINKED ISSUE #31: Dependencies on non-existing messages
**Describe the bug**
Most probably Skynet references temporary message IDs on edit or delete and does not change these dependencies before sending the message to the server.

**To Reproduce**
1. Open a chat in Skynet
2. Disconnect from the server
3. Write a message
4. Edit the message
5. Reconnect to the server
6. Enjoy getting kicked

**Expected behavior**
Skynet should edit the message content as long as the message has not been sent to the server.

**Smartphone**
 - Device: Samsung Galaxy S10+
 - OS: Android 10

**Additional context**
⚠️ Beware of concurrency issues when editing message contents while a send loop is running in the background.

### PR DESCRIPTION
**Pull request by Twometer**
Again, multiple bugfixes and enhancements:

- An old sporadic internal RecyclerView crash
- Improve message state reliability by rewriting packet awaiter
- Some minor improvements 
- Issue #26 
- Issue #20 
- Issue #18 
- Issue #30 
- Issue #31

### CODE REVIEW

File: app/src/main/java/de/vectordata/skynet/net/PacketHandler.java [hunk 1]
```diff
@@ -104,6 +101,12 @@ void handlePacket(byte id, byte[] payload) {
             if (flags != null)
                 if ((message.messageFlags | flags.value()) != message.messageFlags)
                     throw new IllegalStateException(String.format("Incoming channel message lacks required message flags (got: %s, required at least: %d)", message.messageFlags, flags.value()));
+
+            if (message.isCorrupted) {
+                numCorruptedMessages++;
```
Comment (daniel-lerch) [inline app/src/main/java/de/vectordata/skynet/net/PacketHandler.java:106]: As mentioned in #30, it is possible to send corrupted messages intentionally using a modified client.

For chat messages you might be able to use something like `MessageState.Corrupted`. You could reuse the rendering for deleted messages and just change the text to _This message could not be decrypted_.

Corrupted messages with `MessageFlags.Loopback` cannot be caused by a third party. In this case you can increment your counter and show a dialog. Please keep in mind that the client won't be able to decrypt messages from a direct channel if the private keys are corrupted.

File: app/src/main/java/de/vectordata/skynet/ui/base/SkynetActivity.java [hunk 2]
```diff
@@ -46,6 +53,19 @@ public void onAuthenticationFailed(AuthenticationFailedEvent event) {
             Dialogs.showMessageBox(this, R.string.error_header_connect, R.string.error_invalid_session);
     }
 
+    @Subscribe(threadMode = ThreadMode.MAIN)
+    public void onSyncFinished(SyncFinishedEvent event) {
+        int corruptedMessages = SkynetContext.getCurrent().getNetworkManager().getLastSyncCorruptedMessages();
+        if (corruptedMessages > 0) {
```
Comment (daniel-lerch) [inline app/src/main/java/de/vectordata/skynet/ui/base/SkynetActivity.java:59]: What if you receive a corrupted message after sync?

File: app/src/main/java/de/vectordata/skynet/ui/base/SkynetActivity.java [hunk 3]
```diff
@@ -46,6 +53,19 @@ public void onAuthenticationFailed(AuthenticationFailedEvent event) {
...
+            new AlertDialog.Builder(this)
+                    .setTitle(R.string.error_header_sync)
+                    .setMessage(getString(R.string.error_corrupted_messages, corruptedMessages))
+                    .setPositiveButton(R.string.ok, null)
+                    .setNeutralButton(R.string.action_report_issue, (dialog, which) -> startBrowser("https://www.skynet.app/bug"))
```
Comment (daniel-lerch) [inline app/src/main/java/de/vectordata/skynet/ui/base/SkynetActivity.java:64]: Good idea to make reporting as easy as possible but without any further information these reports will be useless for us. Maybe you can open a url like `https://www.skynet.app/bug?title=…&description=…` and mention the affected message IDs. We could look them up in the server database and might be able to find out which packets are often affected.

File: app/src/main/java/de/vectordata/skynet/ui/chat/formatting/MarkdownFormatting.java [hunk 4]
```diff
@@ -0,0 +1,107 @@
...
+            }
+        }
+        return null;
+    }
+
+    private enum Formatting {
+        Bold('*'),
+        Italic('_'),
+        Strikeout('~'),
+        SourceCode('`');
```
Comment (daniel-lerch) [inline app/src/main/java/de/vectordata/skynet/ui/chat/formatting/MarkdownFormatting.java:52]: What do you think of implementing a subset of [CommonMark](https://commonmark.org/) instead of simplified markdown? In my opinion this would lead to less confusion and could be extended easily.

**Review by daniel-lerch — CHANGES_REQUESTED** [review]
There are some things that have to be changed to consider #20 and #30 as resolved.

File: app/src/main/java/de/vectordata/skynet/ui/base/SkynetActivity.java (hunk 2 above)
Comment (Twometer) [reply app/src/main/java/de/vectordata/skynet/ui/base/SkynetActivity.java:59]: The idea here was to not show a dialog every time a corrupted message is received, as to not annoy the user (e.g. if someone does this with a malicious client, you could make anyone's app basically unusable)

File: app/src/main/java/de/vectordata/skynet/net/PacketHandler.java [hunk 5]
```diff
@@ -184,50 +184,39 @@ public void handlePacket(P0CChannelMessageResponse packet) {
...
-                                new AsymmetricKey(KeyFormat.BOUNCY_CASTLE, signature.getPublicKey()),
-                                new AsymmetricKey(KeyFormat.BOUNCY_CASTLE, derivation.getPublicKey())
-                        )
-                );
-            });
-        }
+        Channel loopbackChannel = Storage.getDatabase().channelDao().getByType(Storage.getSession().getAccountId(), ChannelType.LOOPBACK);
+
+        // Check if there are at least two keys (public and private)
+        boolean hasKeys = Storage.getDatabase().channelKeyDao().countKeys(loopbackChannel.getChannelId()) >= 2;
```
[the remark this answers is not in the document]
Comment (Twometer) [reply app/src/main/java/de/vectordata/skynet/net/PacketHandler.java:196]: ah okay must have misread the old code when rewriting it.

File: app/src/main/java/de/vectordata/skynet/net/PacketHandler.java (hunk 1 above)
Comment (Twometer) [reply app/src/main/java/de/vectordata/skynet/net/PacketHandler.java:106]: `MessageState`s only exist for ChatMessages, how should other corrupted channel messages be handled?

File: app/src/main/java/de/vectordata/skynet/ui/base/SkynetActivity.java (hunk 3 above)
Comment (Twometer) [reply app/src/main/java/de/vectordata/skynet/ui/base/SkynetActivity.java:64]: That would also be an extension to the web app...

File: app/src/main/java/de/vectordata/skynet/ui/chat/formatting/MarkdownFormatting.java (hunk 4 above)
Comment (Twometer) [reply app/src/main/java/de/vectordata/skynet/ui/chat/formatting/MarkdownFormatting.java:52]: I wanted to keep it simple because CommonMark parsers are usually not the lightest of libraries. Also, I don't think many people will need paragraph headers and tables in their messages. Maybe we can find a lightweight implementation of something similar in a library, but I haven't found one which is why i threw together this parser.

File: app/src/main/java/de/vectordata/skynet/net/PacketHandler.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (Twometer) [reply app/src/main/java/de/vectordata/skynet/net/PacketHandler.java]: Please see the fix in the latest commit

File: app/src/main/java/de/vectordata/skynet/ui/chat/formatting/MarkdownFormatting.java (hunk 4 above)
Comment (daniel-lerch) [reply app/src/main/java/de/vectordata/skynet/ui/chat/formatting/MarkdownFormatting.java:52]: I see. If we change to CommonMark in the future, the rendering of single asterisk will change from bold to italic but as chat message usually short-lived that won't be a big problem.

File: app/src/main/java/de/vectordata/skynet/net/PacketHandler.java (hunk 1 above)
Comment (daniel-lerch) [reply app/src/main/java/de/vectordata/skynet/net/PacketHandler.java:106]: There are only two types of encrypted channel messages without `MessageFlags.Loopback` which are `P20ChatMessage` and `P21MessageOverride`. Both are connected to a chat message and could use `MessageState.Corrupted`.

File: app/src/main/java/de/vectordata/skynet/ui/base/SkynetActivity.java (hunk 2 above)
Comment (daniel-lerch) [reply app/src/main/java/de/vectordata/skynet/ui/base/SkynetActivity.java:59]: As mentioned above, messages from others can be handled with `MessageState.Corrupted`. Corrupted messages with `MessageFlags.Loopback` can annoy the user. If you want to use a malicious client, you will have to live with the consequences.

Creating only one dialog for the whole sync process is a good idea. You could implement something like this for loopback messages in `PacketHandler.java`:

```java
if (inSync) {
    showDialogForCorruptedMessage();
} else {
    numCorruptedMessages++;
}
```

File: app/src/main/java/de/vectordata/skynet/ui/base/SkynetActivity.java (hunk 3 above)
Comment (daniel-lerch) [reply app/src/main/java/de/vectordata/skynet/ui/base/SkynetActivity.java:64]: You can also show the message ID in the dialog.

For the extension I can open a new feature at [skynet-im/skynet-website](https://github.com/skynet-im/skynet-website). Have you uploaded the source code of this web app?

File: app/src/main/java/de/vectordata/skynet/ui/base/SkynetActivity.java (hunk 2 above)
Comment (Twometer) [reply app/src/main/java/de/vectordata/skynet/ui/base/SkynetActivity.java:59]: But that means that every single corrupted message will show a dialog. What I meant with malicious client was the following scenario:

1. Open a direct channel with someone
2. Start spamming corrupted messages
3. The target will be spammed with dialog messages the second he opens Skynet. He cannot block the attacker because there are dialogs in the way. The account is basically unusable.

As you said only chat messages can be corrupted (as of now, If we have something like the discussed BeginCall, we would have some other issues). I would only show the dialog after sync and keep everything else to a per-message info.

File: app/src/main/java/de/vectordata/skynet/net/PacketHandler.java (hunk 1 above)
Comment (Twometer) [reply app/src/main/java/de/vectordata/skynet/net/PacketHandler.java:106]: Alright makes sense; I will implement taht

File: app/src/main/java/de/vectordata/skynet/ui/base/SkynetActivity.java (hunk 3 above)
Comment (Twometer) [reply app/src/main/java/de/vectordata/skynet/ui/base/SkynetActivity.java:64]: No, it's not uploaded because the webapp is only a temporary app that uses a GitHub API key to make Issues so that betatesters don't have to have a GitHub account

Comment (daniel-lerch) [reply app/src/main/java/de/vectordata/skynet/ui/base/SkynetActivity.java:64]: This problem is now tracked by #32.

File: app/src/main/java/de/vectordata/skynet/net/PacketHandler.java [hunk 6]
```diff
@@ -104,6 +101,11 @@ void handlePacket(byte id, byte[] payload) {
             if (flags != null)
                 if ((message.messageFlags | flags.value()) != message.messageFlags)
                     throw new IllegalStateException(String.format("Incoming channel message lacks required message flags (got: %s, required at least: %d)", message.messageFlags, flags.value()));
+
+            if (message.isCorrupted) {
```
Comment (daniel-lerch) [inline app/src/main/java/de/vectordata/skynet/net/PacketHandler.java:105]: Users should not get annoying dialog windows if someone else is using a malicious client. Marking the respective chat message as corrupted is enough.

```suggestion
            if (message.isCorrupted && ((message.messageFlags & MessageFlags.LOOPBACK) == 1)) {
```

File: app/src/main/java/de/vectordata/skynet/ui/base/SkynetActivity.java (hunk 2 above)
Comment (daniel-lerch) [reply app/src/main/java/de/vectordata/skynet/ui/base/SkynetActivity.java:59]: Only corrupted messages with `MessageFlags.Loopback` will show a dialog (see my suggestion in `PacketHandler.java:105`)

Please implement this second dialog for a single corrupted message that was received after completing the sync like described above.

**Review by daniel-lerch — CHANGES_REQUESTED** [review]

File: app/src/main/java/de/vectordata/skynet/net/PacketHandler.java (hunk 6 above)
Comment (Twometer) [reply app/src/main/java/de/vectordata/skynet/net/PacketHandler.java:105]: So users should not be notified after sync if the client receives corrupted chat messages?

File: app/src/main/java/de/vectordata/skynet/net/PacketHandler.java [hunk 7]
```diff
@@ -365,8 +338,58 @@ public void handlePacket(P33DeviceListResponse packet) {
...
+            return;
+
+        P17PrivateKeys privateKeys = new P17PrivateKeys(signature.getPrivateKey(), derivation.getPrivateKey());
+        P18PublicKeys publicKeys = new P18PublicKeys(signature.getPublicKey(), derivation.getPublicKey());
+
+        // First transmit the private keys
+        SkynetContext.getCurrent().getMessageInterface().send(loopbackChannel.getChannelId(), privateKeys)
+                .waitForSuccess(r -> {
+                    // If that was successful, store them in the database
+                    Storage.getDatabase().channelKeyDao().insert(ChannelKey.fromPacket(privateKeys));
```
Comment (daniel-lerch) [inline app/src/main/java/de/vectordata/skynet/net/PacketHandler.java:358]: This insert operation leads to foreign key constraint violation. I would assume that the channel message entity is missing.

```
android.database.sqlite.SQLiteConstraintException: FOREIGN KEY constraint failed (code 787 SQLITE_CONSTRAINT_FOREIGNKEY)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:796)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at androidx.sqlite.db.framework.FrameworkSQLiteStatement.executeInsert(FrameworkSQLiteStatement.java:51)
        at androidx.room.EntityInsertionAdapter.insert(EntityInsertionAdapter.java:80)
        at de.vectordata.skynet.data.sql.dao.ChannelKeyDao_Impl.insert(ChannelKeyDao_Impl.java:127)
        at de.vectordata.skynet.net.PacketHandler.lambda$regenerateLoopbackKeys$1(PacketHandler.java:358)
        at de.vectordata.skynet.net.-$$Lambda$PacketHandler$bBYhDRvXKwqnJlbPzc31tSdyohI.handle(Unknown Source:8)
        at de.vectordata.skynet.net.response.PacketTask.lambda$waitForSuccess$1(PacketTask.java:50)
        at de.vectordata.skynet.net.response.-$$Lambda$PacketTask$Sl6VMANmQM1q2YYbZeKo49bevp8.handle(Unknown Source:4)
        at de.vectordata.skynet.net.response.PacketTask.lambda$waitForResponse$2$PacketTask(PacketTask.java:68)
        at de.vectordata.skynet.net.response.-$$Lambda$PacketTask$m69dEHnf4uwKOAfbzFBGtf9K5lc.handle(Unknown Source:8)
        at de.vectordata.skynet.net.response.BaseAwaiterItem.handle(BaseAwaiterItem.java:18)
        at de.vectordata.skynet.net.response.PacketTask.onPacketEvent(PacketTask.java:79)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:507)
        at org.greenrobot.eventbus.EventBus.postToSubscription(EventBus.java:430)
        at org.greenrobot.eventbus.EventBus.postSingleEventForEventType(EventBus.java:411)
        at org.greenrobot.eventbus.EventBus.postSingleEvent(EventBus.java:384)
        at org.greenrobot.eventbus.EventBus.post(EventBus.java:265)
        at de.vectordata.skynet.net.PacketHandler.handlePacket(PacketHandler.java:121)
        at de.vectordata.skynet.net.NetworkManager.onPacketReceived(NetworkManager.java:136)
        at de.vectordata.skynet.net.client.SslClient.receiveLoop(SslClient.java:74)
        at de.vectordata.skynet.net.client.SslClient.lambda$connect$0$SslClient(SslClient.java:41)
        at de.vectordata.skynet.net.client.-$$Lambda$SslClient$seCGbRtAjmtpta9VGd0U12rFxRs.run(Unknown Source:6)
        at java.lang.Thread.run(Thread.java:764)
```

**Review by daniel-lerch — CHANGES_REQUESTED** [review]
The handling of corrupted messages is excellent now. Unfortunately, I was unable to send a message because the keypair creation is broken.

File: app/src/main/java/de/vectordata/skynet/net/PacketHandler.java (hunk 7 above)
Comment (Twometer) [reply app/src/main/java/de/vectordata/skynet/net/PacketHandler.java:358]: did you reset the database and use a new server/accounmt, the old client broke all loopback channels?

Comment (Twometer) [reply app/src/main/java/de/vectordata/skynet/net/PacketHandler.java]: Please see latest commit for a fix

**Review by daniel-lerch — APPROVED** [review]
All manual tests passed ✔️
We are ready to release v0.9.1 🚀

**Comment by Twometer** [comment]
Yay
